@echo off
setlocal enabledelayedexpansion
:: ===============================================================
:: Automated Visual Validation for Classification Buffer + Water
:: ===============================================================
::
:: This script:
:: 1. Copies the validation script as game_start.scr
:: 2. Launches OpenTTD with OpenGL, loads a savegame (or new game)
:: 3. game_start.scr runs automatically, captures screenshots, exits
:: 4. Python script compares screenshots for correctness
::
:: Prerequisites:
:: - OpenTTD built in build\Release\openttd.exe
:: - Python 3 available as 'python' or 'py'
::
:: Usage:
::   scripts\run_visual_validation.bat [savegame.sav]
::

set "ROOT=%~dp0.."
set "BUILD_DIR=%ROOT%\build"
set "GAME_EXE=%BUILD_DIR%\Release\openttd.exe"
set "SCRIPT_SRC=%ROOT%\scripts\validate_classification.scr"

:: Check game executable
if not exist "%GAME_EXE%" (
    echo ERROR: Game executable not found at %GAME_EXE%
    echo Build with: cmake --build build --config Release --target openttd
    exit /b 1
)

:: Setup: copy validation script as game_start.scr
if not exist "%BUILD_DIR%\scripts" mkdir "%BUILD_DIR%\scripts"

:: Create game_start.scr that runs our validation then exits
(
echo ; Auto-generated by run_visual_validation.bat
echo ; This runs on game load and captures validation screenshots
echo exec scripts/validate_classification_inner.scr
) > "%BUILD_DIR%\scripts\game_start.scr"

:: Copy the actual validation script
copy /y "%SCRIPT_SRC%" "%BUILD_DIR%\scripts\validate_classification_inner.scr" > nul

:: Determine save game
set "SAVEGAME="
if not "%~1"=="" (
    set "SAVEGAME=-g %~1"
    echo Using savegame: %~1
) else (
    echo No savegame specified, will use new game ^(menu -^> new game needed^)
    echo Tip: Pass a .sav file as argument for fully automated testing
    set "SAVEGAME=-g"
)

echo.
echo === Launching OpenTTD for visual validation ===
echo.

:: Launch game with OpenGL, fixed resolution, savegame
start /wait "" "%GAME_EXE%" -v win32-opengl -r 1280x720 %SAVEGAME% -x

echo.
echo === Game exited. Checking screenshots ===
echo.

:: Find screenshot directory (common locations)
set "SS_DIR="
for %%d in (
    "%USERPROFILE%\Documents\OpenTTD\screenshot"
    "%USERPROFILE%\OneDrive\Documents\OpenTTD\screenshot"
    "%APPDATA%\OpenTTD\screenshot"
) do (
    if exist "%%~d" set "SS_DIR=%%~d"
)

if "!SS_DIR!"=="" (
    echo ERROR: Could not find OpenTTD screenshot directory
    echo Checked: Documents\OpenTTD\screenshot, AppData\OpenTTD\screenshot
    exit /b 1
)

echo Screenshot directory: !SS_DIR!
echo.

:: Count validation screenshots
set "COUNT=0"
for %%f in ("!SS_DIR!\vc_*.bmp") do set /a COUNT+=1
echo Found %COUNT% validation screenshots

:: Run Python comparison
where python >nul 2>&1
if %errorlevel%==0 (
    python "%ROOT%\scripts\compare_screenshots.py" "!SS_DIR!" --prefix vc_
) else (
    where py >nul 2>&1
    if %errorlevel%==0 (
        py "%ROOT%\scripts\compare_screenshots.py" "!SS_DIR!" --prefix vc_
    ) else (
        echo WARNING: Python not found. Manual screenshot comparison needed.
        echo Screenshots are in: !SS_DIR!
        dir "!SS_DIR!\vc_*.bmp"
    )
)

:: Cleanup game_start.scr
echo ; Normal startup > "%BUILD_DIR%\scripts\game_start.scr"

echo.
echo === Done ===
endlocal
