#!/bin/bash
# ===============================================================
# Automated A/B Visual Comparison: Vanilla OpenTTD vs Modded
# ===============================================================
#
# This script:
# 1. Creates a deterministic savegame using vanilla OpenTTD
# 2. Captures golden reference screenshots from vanilla
# 3. Loads the SAME savegame in the modded build
# 4. Captures comparison screenshots (PP-off and PP-on)
# 5. Runs PSNR comparison between vanilla and modded
#
# Prerequisites:
#   - Vanilla OpenTTD built at: ../OpenTTD-vanilla/build/Release/openttd.exe
#   - Modded OpenTTD built at:  ./build/Release/openttd.exe
#   - Python 3 available
#   - Both builds need baseset (graphics) to render
#
# Usage:
#   ./scripts/run_ab_comparison.sh [--seed 12345] [--timeout 45]
#
# ===============================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VANILLA_DIR="$(cd "$ROOT_DIR/../OpenTTD-vanilla" 2>/dev/null && pwd || echo "")"
MODDED_DIR="$ROOT_DIR"

# Defaults
SEED="${SEED:-424242}"
TIMEOUT="${TIMEOUT:-45}"
RESOLUTION="1280x720"

# Parse args
while [[ $# -gt 0 ]]; do
    case $1 in
        --seed) SEED="$2"; shift 2 ;;
        --timeout) TIMEOUT="$2"; shift 2 ;;
        *) echo "Unknown arg: $1"; exit 1 ;;
    esac
done

# --- Validate builds exist ---
VANILLA_EXE="$VANILLA_DIR/build/Release/openttd.exe"
MODDED_EXE="$MODDED_DIR/build/Release/openttd.exe"

if [ ! -f "$VANILLA_EXE" ]; then
    echo "ERROR: Vanilla OpenTTD not found at $VANILLA_EXE"
    echo "Build it with:"
    echo "  cd ../OpenTTD-vanilla/build && cmake --build . --config Release --target openttd"
    exit 1
fi

if [ ! -f "$MODDED_EXE" ]; then
    echo "ERROR: Modded OpenTTD not found at $MODDED_EXE"
    echo "Build it with:"
    echo "  cd build && cmake --build . --config Release --target openttd"
    exit 1
fi

echo "=============================================="
echo "  A/B Visual Comparison Pipeline"
echo "=============================================="
echo "  Seed:       $SEED"
echo "  Resolution: $RESOLUTION"
echo "  Timeout:    ${TIMEOUT}s per run"
echo "  Vanilla:    $VANILLA_EXE"
echo "  Modded:     $MODDED_EXE"
echo "=============================================="
echo ""

# --- Setup output directories ---
OUTPUT_DIR="$ROOT_DIR/ab_comparison_output"
VANILLA_SS_DIR="$OUTPUT_DIR/vanilla"
MODDED_SS_DIR="$OUTPUT_DIR/modded"
GOLDEN_DIR="$OUTPUT_DIR/golden"
SAVEGAME_DIR="$OUTPUT_DIR/saves"

rm -rf "$OUTPUT_DIR"
mkdir -p "$VANILLA_SS_DIR" "$MODDED_SS_DIR" "$GOLDEN_DIR" "$SAVEGAME_DIR"

# --- Step 1: Create savegame with vanilla OpenTTD ---
echo "=== Step 1: Creating deterministic savegame with vanilla ==="

# Create a script that generates a map, saves it, takes screenshots, and exits
VANILLA_BUILD_DIR="$VANILLA_DIR/build"
mkdir -p "$VANILLA_BUILD_DIR/scripts"

cat > "$VANILLA_BUILD_DIR/scripts/game_start.scr" << ENDSCRIPT
; Auto-generated by run_ab_comparison.sh
pause

; Save the game for reuse by modded build
save ab_reference

; Take golden reference screenshots at each zoom level
zoomto 0
screenshot viewport no_con golden_01_zoom_in4x

zoomto 1
screenshot viewport no_con golden_02_zoom_in2x

zoomto 2
screenshot viewport no_con golden_03_zoom_normal

zoomto 3
screenshot viewport no_con golden_04_zoom_out2x

zoomto 4
screenshot viewport no_con golden_05_zoom_out4x

zoomto 2
screenshot minimap golden_06_minimap

exit
ENDSCRIPT

echo "  Launching vanilla OpenTTD (seed=$SEED, timeout=${TIMEOUT}s)..."

# Run vanilla OpenTTD with deterministic seed
cd "$VANILLA_BUILD_DIR"
timeout "$TIMEOUT" ./Release/openttd.exe \
    -v win32-opengl \
    -r "$RESOLUTION" \
    -G "$SEED" \
    -g \
    -x \
    -Q \
    2>/dev/null || true

echo "  Vanilla run complete."

# --- Find and collect vanilla outputs ---
echo "  Collecting vanilla screenshots and savegame..."

# Find the OpenTTD user directory (screenshots and saves go there)
OTTD_USER_DIR=""
for dir in \
    "$USERPROFILE/Documents/OpenTTD" \
    "$HOME/Documents/OpenTTD" \
    "$APPDATA/OpenTTD" \
    ; do
    expanded=$(ls -d $dir 2>/dev/null | head -1)
    if [ -n "$expanded" ] && [ -d "$expanded" ]; then
        OTTD_USER_DIR="$expanded"
        break
    fi
done

if [ -z "$OTTD_USER_DIR" ]; then
    echo "WARNING: Could not find OpenTTD user directory. Searching..."
    OTTD_USER_DIR=$(find "$HOME" -maxdepth 5 -path "*/OpenTTD/save" -type d 2>/dev/null | head -1 | sed 's|/save$||')
fi

if [ -z "$OTTD_USER_DIR" ]; then
    echo "ERROR: Cannot find OpenTTD user directory"
    exit 1
fi

echo "  OpenTTD user dir: $OTTD_USER_DIR"

# Copy savegame
if [ -f "$OTTD_USER_DIR/save/ab_reference.sav" ]; then
    cp "$OTTD_USER_DIR/save/ab_reference.sav" "$SAVEGAME_DIR/"
    echo "  Savegame: OK"
else
    echo "  WARNING: Savegame not found. Vanilla may not have saved."
fi

# Copy golden screenshots
FOUND=0
for f in "$OTTD_USER_DIR/screenshot"/golden_*.png "$OTTD_USER_DIR/screenshot"/golden_*.bmp; do
    if [ -f "$f" ]; then
        cp "$f" "$GOLDEN_DIR/"
        FOUND=$((FOUND + 1))
    fi
done
echo "  Golden screenshots: $FOUND found"

# Cleanup vanilla game_start.scr
echo "; normal startup" > "$VANILLA_BUILD_DIR/scripts/game_start.scr"

# --- Step 2: Run modded OpenTTD with same savegame ---
echo ""
echo "=== Step 2: Capturing modded screenshots with same savegame ==="

MODDED_BUILD_DIR="$MODDED_DIR/build"
mkdir -p "$MODDED_BUILD_DIR/scripts"

# Copy savegame to modded save directory so it can be loaded
mkdir -p "$OTTD_USER_DIR/save"
cp "$SAVEGAME_DIR/ab_reference.sav" "$OTTD_USER_DIR/save/" 2>/dev/null || true

cat > "$MODDED_BUILD_DIR/scripts/game_start.scr" << 'ENDSCRIPT'
; Auto-generated by run_ab_comparison.sh
pause

; === Part A: PP-OFF (should match vanilla) ===
pp off

zoomto 0
screenshot viewport no_con modded_01_ppoff_zoom_in4x

zoomto 1
screenshot viewport no_con modded_02_ppoff_zoom_in2x

zoomto 2
screenshot viewport no_con modded_03_ppoff_zoom_normal

zoomto 3
screenshot viewport no_con modded_04_ppoff_zoom_out2x

zoomto 4
screenshot viewport no_con modded_05_ppoff_zoom_out4x

zoomto 2
screenshot minimap modded_06_ppoff_minimap

; === Part B: PP-ON with ship effects ===
pp on
pp enable fxaa
pp set sharpening 50
pp enable vignette

zoomto 0
pp_screenshot modded_07_ppon_zoom_in4x

zoomto 1
pp_screenshot modded_08_ppon_zoom_in2x

zoomto 2
pp_screenshot modded_09_ppon_zoom_normal

zoomto 3
pp_screenshot modded_10_ppon_zoom_out2x

zoomto 4
pp_screenshot modded_11_ppon_zoom_out4x

; === Part C: Classification debug ===
zoomto 2
pp debug_class on
pp_screenshot modded_12_debug_class

; === Part D: Water with class_tex ===
pp debug_class off
pp enable water
pp_screenshot modded_13_water_on

pp enable night
pp_screenshot modded_14_water_night

; === Restore ===
pp off

exit
ENDSCRIPT

echo "  Launching modded OpenTTD (loading ab_reference.sav, timeout=${TIMEOUT}s)..."

cd "$MODDED_BUILD_DIR"
timeout "$TIMEOUT" ./Release/openttd.exe \
    -v win32-opengl \
    -r "$RESOLUTION" \
    -g "$OTTD_USER_DIR/save/ab_reference.sav" \
    -x \
    -Q \
    2>/dev/null || true

echo "  Modded run complete."

# --- Collect modded screenshots ---
echo "  Collecting modded screenshots..."
FOUND=0
for f in "$OTTD_USER_DIR/screenshot"/modded_*.png "$OTTD_USER_DIR/screenshot"/modded_*.bmp; do
    if [ -f "$f" ]; then
        cp "$f" "$MODDED_SS_DIR/"
        FOUND=$((FOUND + 1))
    fi
done
echo "  Modded screenshots: $FOUND found"

# Cleanup modded game_start.scr
echo "; normal startup" > "$MODDED_BUILD_DIR/scripts/game_start.scr"

# --- Step 3: Compare screenshots ---
echo ""
echo "=== Step 3: Comparing screenshots ==="
echo ""

# Create comparison Python script inline
cat > "$OUTPUT_DIR/compare.py" << 'ENDPYTHON'
#!/usr/bin/env python3
"""Compare vanilla golden references against modded screenshots."""
import sys, os, math, glob

def load_bmp(path):
    with open(path, 'rb') as f:
        hdr = f.read(54)
        if hdr[:2] != b'BM': raise ValueError(f"Not BMP: {path}")
        off = int.from_bytes(hdr[10:14], 'little')
        w = abs(int.from_bytes(hdr[18:22], 'little', signed=True))
        h = abs(int.from_bytes(hdr[22:26], 'little', signed=True))
        bpp = int.from_bytes(hdr[28:30], 'little')
        Bpp = bpp // 8; row = ((w * Bpp + 3) & ~3)
        f.seek(off); raw = f.read(row * h)
        px = []
        for y in range(h):
            ro = (h - 1 - y) * row
            for x in range(w):
                po = ro + x * Bpp
                px.append((raw[po+2], raw[po+1], raw[po]))
        return w, h, px

def load_png_as_bmp_fallback(path):
    """Try loading as BMP first, if that fails try to use PIL for PNG."""
    try:
        return load_bmp(path)
    except (ValueError, IndexError):
        try:
            from PIL import Image
            im = Image.open(path).convert('RGB')
            w, h = im.size
            px = list(im.getdata())
            return w, h, px
        except ImportError:
            raise ValueError(f"Cannot load {path}: not BMP and PIL not available")

def psnr(px1, px2):
    if len(px1) != len(px2): return 0.0, 999.0, 999
    mse = sum(sum((a-b)**2 for a,b in zip(p1,p2)) for p1,p2 in zip(px1,px2)) / (len(px1)*3)
    if mse == 0: return float('inf'), 0.0, 0
    return 10*math.log10(65025/mse), math.sqrt(mse), max(max(abs(a-b) for a,b in zip(p1,p2)) for p1,p2 in zip(px1,px2))

def find_images(d, prefix):
    imgs = {}
    for ext in ('*.bmp', '*.png'):
        for p in glob.glob(os.path.join(d, f"{prefix}{ext}")):
            imgs[os.path.splitext(os.path.basename(p))[0]] = p
    return imgs

def main():
    golden_dir = sys.argv[1] if len(sys.argv) > 1 else "golden"
    modded_dir = sys.argv[2] if len(sys.argv) > 2 else "modded"

    golden = find_images(golden_dir, "golden_")
    modded_ppoff = find_images(modded_dir, "modded_")

    print("=" * 70)
    print("  A/B COMPARISON RESULTS")
    print("=" * 70)
    passes, fails, warnings = [], [], []

    # --- Test 1: Vanilla vs Modded PP-OFF (should be near-identical) ---
    print("\n--- Test 1: Vanilla vs Modded (PP off) ---")
    print("  These should be nearly identical.\n")
    zoom_pairs = [
        ("golden_01_zoom_in4x",  "modded_01_ppoff_zoom_in4x"),
        ("golden_02_zoom_in2x",  "modded_02_ppoff_zoom_in2x"),
        ("golden_03_zoom_normal", "modded_03_ppoff_zoom_normal"),
        ("golden_04_zoom_out2x", "modded_04_ppoff_zoom_out2x"),
        ("golden_05_zoom_out4x", "modded_05_ppoff_zoom_out4x"),
    ]

    for g_name, m_name in zoom_pairs:
        g_path = golden.get(g_name)
        m_path = modded_ppoff.get(m_name)
        if not g_path or not m_path:
            msg = f"  SKIP: {g_name} or {m_name} missing"
            print(msg); warnings.append(msg)
            continue
        try:
            w1,h1,px1 = load_png_as_bmp_fallback(g_path)
            w2,h2,px2 = load_png_as_bmp_fallback(m_path)
            if w1 != w2 or h1 != h2:
                msg = f"  FAIL: {g_name} size mismatch ({w1}x{h1} vs {w2}x{h2})"
                print(msg); fails.append(msg); continue
            p, md, mx = psnr(px1, px2)
            if p == float('inf'):
                print(f"  PASS: {g_name} -- pixel-identical")
                passes.append(f"vanilla_vs_ppoff_{g_name}")
            elif p > 30:
                print(f"  PASS: {g_name} -- PSNR={p:.1f}dB (mean_diff={md:.2f}, max={mx})")
                passes.append(f"vanilla_vs_ppoff_{g_name}: PSNR={p:.1f}")
            else:
                msg = f"  WARN: {g_name} -- PSNR={p:.1f}dB (may have rendering differences)"
                print(msg); warnings.append(msg)
        except Exception as e:
            print(f"  ERROR: {g_name}: {e}")
            warnings.append(str(e))

    # --- Test 2: PP-OFF vs PP-ON (effects should produce visible change) ---
    print("\n--- Test 2: PP-off vs PP-on (should differ) ---")
    print("  Post-processing should produce visible improvements.\n")
    ppoff_on_pairs = [
        ("modded_01_ppoff_zoom_in4x",  "modded_07_ppon_zoom_in4x"),
        ("modded_02_ppoff_zoom_in2x",  "modded_08_ppon_zoom_in2x"),
        ("modded_03_ppoff_zoom_normal", "modded_09_ppon_zoom_normal"),
        ("modded_04_ppoff_zoom_out2x",  "modded_10_ppon_zoom_out2x"),
        ("modded_05_ppoff_zoom_out4x",  "modded_11_ppon_zoom_out4x"),
    ]

    for off_name, on_name in ppoff_on_pairs:
        off_path = modded_ppoff.get(off_name)
        on_path = modded_ppoff.get(on_name)
        if not off_path or not on_path:
            msg = f"  SKIP: {off_name} or {on_name} missing"
            print(msg); warnings.append(msg)
            continue
        try:
            w1,h1,px1 = load_png_as_bmp_fallback(off_path)
            w2,h2,px2 = load_png_as_bmp_fallback(on_path)
            if w1 != w2 or h1 != h2:
                msg = f"  WARN: {off_name} size mismatch (PP-on may use different capture path)"
                print(msg); warnings.append(msg); continue
            p, md, mx = psnr(px1, px2)
            if p == float('inf') or p > 50:
                msg = f"  WARN: {off_name} -- PP-on looks identical (PSNR={p:.1f}dB)"
                print(msg); warnings.append(msg)
            else:
                print(f"  OK:   {off_name} -- effects visible (PSNR={p:.1f}dB, mean_diff={md:.2f})")
                passes.append(f"ppoff_vs_ppon_{off_name}: PSNR={p:.1f}")
        except Exception as e:
            print(f"  ERROR: {off_name}: {e}")

    # --- Test 3: Classification debug view ---
    print("\n--- Test 3: Classification debug view ---")
    debug_path = modded_ppoff.get("modded_12_debug_class")
    if debug_path:
        try:
            w,h,px = load_png_as_bmp_fallback(debug_path)
            # Count distinct colour clusters (debug view should have 4+ distinct colours)
            from collections import Counter
            # Quantize to 32-level bins
            quantized = Counter((r//32, g//32, b//32) for r,g,b in px)
            n_clusters = len([c for c,n in quantized.items() if n > len(px)*0.01])
            if n_clusters >= 3:
                print(f"  PASS: {n_clusters} distinct colour regions detected")
                passes.append(f"debug_class: {n_clusters} clusters")
            else:
                msg = f"  WARN: Only {n_clusters} colour regions (expected 3+)"
                print(msg); warnings.append(msg)
        except Exception as e:
            print(f"  ERROR: {e}")
    else:
        print("  SKIP: debug_class screenshot not found")

    # --- Test 4: Water effect ---
    print("\n--- Test 4: Water effect ---")
    normal = modded_ppoff.get("modded_09_ppon_zoom_normal")
    water = modded_ppoff.get("modded_13_water_on")
    if normal and water:
        try:
            w1,h1,px1 = load_png_as_bmp_fallback(normal)
            w2,h2,px2 = load_png_as_bmp_fallback(water)
            if w1 == w2 and h1 == h2:
                p, md, mx = psnr(px1, px2)
                if p < 50:
                    print(f"  PASS: Water effect visible (PSNR={p:.1f}dB vs no-water)")
                    passes.append(f"water_effect: PSNR={p:.1f}")
                else:
                    msg = f"  WARN: Water effect not visible (PSNR={p:.1f}dB)"
                    print(msg); warnings.append(msg)
        except Exception as e:
            print(f"  ERROR: {e}")
    else:
        print("  SKIP: water screenshots missing")

    # --- Summary ---
    print("\n" + "=" * 70)
    print(f"  PASSES:   {len(passes)}")
    print(f"  WARNINGS: {len(warnings)}")
    print(f"  FAILURES: {len(fails)}")
    print("=" * 70)

    if fails:
        print("\nFAILURES:")
        for f in fails: print(f"  {f}")
        return 1
    elif warnings:
        print("\nAll critical checks passed. Some warnings to review.")
        return 0
    else:
        print("\nAll checks passed.")
        return 0

if __name__ == '__main__':
    sys.exit(main())
ENDPYTHON

# Run comparison
if command -v python3 &>/dev/null; then
    PYTHON=python3
elif command -v python &>/dev/null; then
    PYTHON=python
elif command -v py &>/dev/null; then
    PYTHON=py
else
    echo "ERROR: Python not found"
    exit 1
fi

$PYTHON "$OUTPUT_DIR/compare.py" "$GOLDEN_DIR" "$MODDED_SS_DIR"
RESULT=$?

echo ""
echo "=============================================="
echo "  Output directory: $OUTPUT_DIR"
echo "  Golden refs:      $GOLDEN_DIR/"
echo "  Modded captures:  $MODDED_SS_DIR/"
echo "  Savegame:         $SAVEGAME_DIR/ab_reference.sav"
echo "=============================================="

exit $RESULT
